version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    ports:
    - "8080:8080"
    volumes:
    - .:/data
    depends_on:
    - db
    environment:
     DATABASE_URL: postgres://postgres@db/postgres
  db:
    image: postgres:9.5
