# Generated by Django 2.1.3 on 2018-11-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181122_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
